SELECT sup.SUPPLIERNAME,
	ctc.SUPPLIERCONTACTNAME,
	LEFT(ctc.PHONENO1, 4) + '-' + RIGHT(ctc.PHONENO1, 4) AS PHONENO1,
	LEFT(ctc.PHONENO2, 4) + '-' + RIGHT(ctc.PHONENO2, 4) AS PHONENO2,
	ordh.TOTALORDERS,
	REPLACE(FORMAT(ordh.ORDERTOTALAMOUNT, 'C'), '$', '') AS ORDERTOTALAMOUNT
--Supplier
FROM XXBCM_CLIENT sup
--Order
LEFT JOIN ( SELECT SUPPLIERID,
				COUNT(*) AS TOTALORDERS,
				SUM(ORDERTOTALAMOUNT) ORDERTOTALAMOUNT
			FROM XXBCM_ORDER_HEADER ordh
			WHERE CONVERT(DATE, ordh.ORDERDATE, 102) BETWEEN '2022-01-01' AND '2022-08-31'
			GROUP BY SUPPLIERID ) AS ordh ON ordh.SUPPLIERID = sup.SUPPLIERID
--Phone Number
LEFT JOIN ( SELECT SUPPLIERID,
			SUPPLIERCONTACTNAME,
			REVERSE(PARSENAME(REPLACE(REVERSE(PHONENUMBER), ',', '.'), 1)) AS PHONENO1,
			REVERSE(PARSENAME(REPLACE(REVERSE(PHONENUMBER), ',', '.'), 2)) AS PHONENO2
		FROM XXBCM_CLIENT_PHONE_NUMBER ) AS ctc ON ctc.SUPPLIERID = ordh.SUPPLIERID
ORDER BY sup.SUPPLIERNAME