
 --Data Cleansing of table XXBCM_ORDER_MGT
--Order line amount
UPDATE XXBCM_ORDER_MGT
SET INVOICE_AMOUNT = REPLACE(INVOICE_AMOUNT, ',', '')

UPDATE XXBCM_ORDER_MGT
SET INVOICE_AMOUNT = 0
WHERE INVOICE_AMOUNT IS NULL

UPDATE XXBCM_ORDER_MGT
SET INVOICE_AMOUNT = REPLACE(INVOICE_AMOUNT, 'O', 0)

UPDATE XXBCM_ORDER_MGT
SET INVOICE_AMOUNT = REPLACE(INVOICE_AMOUNT, 'I', 1)

UPDATE XXBCM_ORDER_MGT
SET INVOICE_AMOUNT = REPLACE(INVOICE_AMOUNT, 'S', 5)

--Order line amount
UPDATE XXBCM_ORDER_MGT
SET ORDER_LINE_AMOUNT = REPLACE(ORDER_LINE_AMOUNT, ',', '')

UPDATE XXBCM_ORDER_MGT
SET ORDER_LINE_AMOUNT = 0
WHERE ORDER_LINE_AMOUNT IS NULL

UPDATE XXBCM_ORDER_MGT
SET ORDER_LINE_AMOUNT = REPLACE(ORDER_LINE_AMOUNT, 'O', 0)

UPDATE XXBCM_ORDER_MGT
SET ORDER_LINE_AMOUNT = REPLACE(ORDER_LINE_AMOUNT, 'I', 1)

UPDATE XXBCM_ORDER_MGT
SET ORDER_LINE_AMOUNT = REPLACE(ORDER_LINE_AMOUNT, 'S', 5)

--Order total amount
UPDATE XXBCM_ORDER_MGT
SET ORDER_TOTAL_AMOUNT = REPLACE(ORDER_TOTAL_AMOUNT, ',', '')

UPDATE XXBCM_ORDER_MGT
SET ORDER_TOTAL_AMOUNT = 0
WHERE ORDER_TOTAL_AMOUNT IS NULL


--Email Address
INSERT INTO XXBCM_CLIENT_EMAIL_ADDRESS
SELECT clt.SUPPLIERID,
	ct.SUPP_CONTACT_NAME,
	ct.SUPP_EMAIL
FROM XXBCM_CLIENT clt
LEFT JOIN ( SELECT DISTINCT SUPPLIER_NAME,
				SUPP_CONTACT_NAME,
				SUPP_EMAIL
			FROM XXBCM_ORDER_MGT ) AS ct
		ON ct.SUPPLIER_NAME COLLATE DATABASE_DEFAULT = clt.SUPPLIERNAME COLLATE DATABASE_DEFAULT


--Client Phone Number
INSERT INTO XXBCM_CLIENT_PHONE_NUMBER
SELECT clt.SUPPLIERID,
	ct.SUPP_CONTACT_NAME,
	ct.SUPP_CONTACT_NUMBER
FROM XXBCM_CLIENT clt
LEFT JOIN ( SELECT DISTINCT SUPPLIER_NAME,
				SUPP_CONTACT_NAME,
				SUPP_CONTACT_NUMBER
			FROM XXBCM_ORDER_MGT ) AS ct
		ON ct.SUPPLIER_NAME COLLATE DATABASE_DEFAULT = clt.SUPPLIERNAME COLLATE DATABASE_DEFAULT


--Order Status
INSERT INTO XXBCM_ORDER_STATUS
SELECT DISTINCT ORDER_STATUS
FROM XXBCM_ORDER_MGT
WHERE ORDER_LINE_AMOUNT IS NULL
ORDER BY ORDER_STATUS


--Order Line Status
INSERT INTO XXBCM_ORDER_LINE_STATUS
SELECT DISTINCT ORDER_STATUS
FROM XXBCM_ORDER_MGT
WHERE ORDER_LINE_AMOUNT IS NOT NULL
ORDER BY ORDER_STATUS


--Invoice status
INSERT INTO XXBCM_INVOICE_STATUS
SELECT DISTINCT INVOICE_STATUS
FROM XXBCM_ORDER_MGT
ORDER BY INVOICE_STATUS


--Invoice hold reason
INSERT INTO XXBCM_INVOICE_HOLD_REASON
SELECT DISTINCT INVOICE_HOLD_REASON
FROM XXBCM_ORDER_MGT
ORDER BY INVOICE_HOLD_REASON


--Client
INSERT INTO XXBCM_CLIENT
SELECT DISTINCT SUPPLIER_NAME
FROM XXBCM_ORDER_MGT


--Order Header
INSERT INTO XXBCM_ORDER_HEADER
SELECT ord.ORDER_REF,
	clt.SUPPLIERID,
	CONVERT(DATETIME, ord.ORDER_DATE, 102) AS ORDERDATE,
	CAST(ord.ORDER_TOTAL_AMOUNT AS DECIMAL(18, 2)) AS ORDERTOTALAMOUNT,
	ord.ORDER_DESCRIPTION AS ORDERDESCRIPTION,
	STS.ORDERSTATUSID
FROM XXBCM_ORDER_MGT ord
LEFT JOIN XXBCM_CLIENT clt ON clt.SUPPLIERNAME COLLATE DATABASE_DEFAULT = ord.SUPPLIER_NAME COLLATE DATABASE_DEFAULT
LEFT JOIN XXBCM_ORDER_STATUS sts ON sts.ORDERSTATUSDESCRIPTION COLLATE DATABASE_DEFAULT = ORD.ORDER_STATUS COLLATE DATABASE_DEFAULT
WHERE ord.ORDER_LINE_AMOUNT = 0


--Order Line
INSERT INTO XXBCM_ORDER_LINE
SELECT ord.ORDER_REF AS ORDERLINEREF,
	ordh.ORDERHEADERID,
	ord.ORDER_DESCRIPTION AS ORDERDESCRIPTION,
	CAST(ord.ORDER_LINE_AMOUNT AS DECIMAL(18, 2)) AS ORDER_LINE_AMOUNT,
	sts.ORDERLINESTATUSID
FROM XXBCM_ORDER_MGT ord
LEFT JOIN XXBCM_ORDER_LINE_STATUS sts ON sts.ORDERLINESTATUSDESCRIPTION COLLATE DATABASE_DEFAULT = ord.ORDER_STATUS COLLATE DATABASE_DEFAULT
LEFT JOIN XXBCM_ORDER_HEADER ordh ON ordh.ORDERREF COLLATE DATABASE_DEFAULT = LEFT(ord.ORDER_REF, 5) COLLATE DATABASE_DEFAULT
WHERE ord.ORDER_LINE_AMOUNT <> 0


--Invoice sent
INSERT INTO XXBCM_INVOICE
SELECT ordh.ORDERHEADERID,
	ord.INVOICE_REFERENCE,
	CONVERT(DATETIME, ord.INVOICE_DATE, 103) AS INVOICE_DATE,
	CAST(ord.INVOICE_AMOUNT AS DECIMAL(18, 2)) AS INVOICE_AMOUNT,
	ists.INVOICESTATUSID,
	hsts.INVOICEHOLDREASONID,
	ord.INVOICE_DESCRIPTION AS INVOICEDESCRIPTION
FROM XXBCM_ORDER_MGT ord
LEFT JOIN XXBCM_INVOICE_STATUS ists ON ists.INVOICESTATUSDESCRIPTION COLLATE DATABASE_DEFAULT = ord.INVOICE_STATUS COLLATE DATABASE_DEFAULT
LEFT JOIN XXBCM_INVOICE_HOLD_REASON hsts ON hsts.INVOICEHOLDREASON COLLATE DATABASE_DEFAULT = ord.INVOICE_HOLD_REASON COLLATE DATABASE_DEFAULT
LEFT JOIN XXBCM_ORDER_HEADER ordh ON ordh.ORDERREF COLLATE DATABASE_DEFAULT = LEFT(ord.ORDER_REF, 5) COLLATE DATABASE_DEFAULT
WHERE ord.ORDER_LINE_AMOUNT <> 0
AND ord.INVOICE_AMOUNT <> 0







