SELECT REPLACE(ordh.ORDERREF, 'PO', '') AS ORDERREF,
	FORMAT(ordh.ORDERDATE, 'MMMM dd, yyyy') AS ORDERDATE,
	UPPER(sup.SUPPLIERNAME) AS SUPPLIERNAME,
	REPLACE(FORMAT(ordh.ORDERTOTALAMOUNT, 'C'), '$', '') AS ORDERTOTALAMOUNT,
	ords.ORDERSTATUSDESCRIPTION AS ORDERSTATUS,
	invRef.INVOICEREFERENCE
--Order Header
FROM XXBCM_ORDER_HEADER ordh
--Supplier
INNER JOIN XXBCM_CLIENT sup ON sup.SUPPLIERID = ordh.SUPPLIERID
--Order Status
INNER JOIN XXBCM_ORDER_STATUS ords ON ords.ORDERSTATUSID =	ordh.ORDERSTATUSID
--Invoice References
LEFT JOIN ( SELECT ORDERHEADERID,
			STRING_AGG(INVOICEREFERENCE, '|') AS INVOICEREFERENCE
			FROM XXBCM_INVOICE
			GROUP BY ORDERHEADERID ) AS invRef ON invRef.ORDERHEADERID = ordh.ORDERHEADERID
WHERE ordh.ORDERHEADERID = ( SELECT TOP 1(ordh.ORDERHEADERID) AS ORDERHEADERID
				FROM XXBCM_ORDER_HEADER ordh
				WHERE ordh.ORDERTOTALAMOUNT < ( SELECT MAX(ORDERTOTALAMOUNT) FROM XXBCM_ORDER_HEADER)
				ORDER BY ordh.ORDERTOTALAMOUNT DESC)
ORDER BY ordh.ORDERTOTALAMOUNT DESC